# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='Address_photo/')),
                ('description', models.CharField(default='', max_length=500)),
                ('location', models.CharField(default='40.440624,-79.995888', max_length=200)),
                ('image_reference', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(default='40.440624,-79.995888', max_length=200)),
                ('picture', models.ImageField(blank=True, upload_to='Attraction_photo/')),
                ('description', models.CharField(max_length=500)),
                ('image_reference', models.CharField(max_length=500)),
                ('formatted_address', models.CharField(max_length=200, null=True)),
                ('formatted_phone_number', models.CharField(max_length=200, null=True)),
                ('international_phone_number', models.CharField(max_length=200, null=True)),
                ('rating', models.CharField(max_length=200, null=True)),
                ('reference', models.CharField(max_length=200, null=True)),
                ('map_url', models.CharField(max_length=200, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Address')),
            ],
        ),
        migrations.CreateModel(
            name='DayTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, upload_to='Profile_photo/')),
                ('token', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('origin', models.CharField(max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.IntegerField(null=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Attraction')),
                ('dayTrip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.DayTrip')),
            ],
            options={
                'ordering': ('schedule',),
            },
        ),
        migrations.AddField(
            model_name='daytrip',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripPlanner.Trip'),
        ),
    ]
