# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 02:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attraction',
            old_name='reference',
            new_name='attr_reference',
        ),
    ]
