# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripPlanner', '0003_auto_20161201_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attraction',
            name='formatted_address',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='price',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='rating',
            field=models.CharField(default='None', max_length=5),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='tag',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
